# # Docker
# # Build a Docker image
# # https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

# resources:
# - repo: self

# variables:
#   tag: '$(Build.BuildId)'

# stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(/agent/_work/1/s/)MyMvcApp/Dockerfile'
#         tags: |
#           $(tag)
trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'P5-Real Hands-On Labs(80ea84e8-afce-4851-928a-9e2219724c69)' # replace with your service connection
        repository: 'mymvcapp1'                           # your Docker image name
        command: 'buildAndPush'
        dockerfile: 'DockerDeployDemo1/Dockerfile'               # path relative to repo root
        tags: |
          $(tag)

